### ISSUE TITLE
Kotlin?

### ISSUE THREAD

**Issue by StefanOltmann** [pitschr/knx-link#81]
What do you think about migrating this project to Kotlin?

Maybe you could also eliminate the need for a JVM and make it this way compatible with Kotlin Native?

It looks small and clean enough to be easily migrated using the tooling in IDEA.

I think there is potential to become the first and only KNX kotlin library (as far as I can see).

**Comment by pitschr** [comment]
Unfortunately, I am not familiar with Kotlin although I am interested in Kotlin. As long my employer is using Java as primary language, I am not feeling skilled enough to provide a Kotlin project for the Koltin community.

You may fork out my project and provide a Kotlin version?

In my spare time I rather invest my energy in the KNX logic engine which will be released in 2021 (hopefully!)

**Comment by StefanOltmann** [comment]
I also only use Java at work and look into Kotlin in my spare time. It's really easy to learn. Kotlin is basicly Java but better. ;)

I will take a look how far I get with automatic conversion and manual rework.

Thank you for your answer.
