### ISSUE TITLE
DPT5.SCALING.of() should take 0..100% range as input

### ISSUE THREAD

**Issue by StefanOltmann** [pitschr/knx-link#91]
`DPT5.SCALING` (_5.001_) and `DPT5.PERCENT_U8` (_5.004_) seem only to differ in the output for `getUnsignedValue()`.

It would make sense if the 0..100% range would also apply to to the `of(int value)` method.

In ETS5 the "Send value" dialog (the one for writing values to group addresses) also takes the 0..100% range for DPT 5.001 (as it takes 0..255% range for DPT 5.004).

Right now I need to convert the 100%-based value to an 255%-based value when calling `DPT5.SCALING.of(percentage)`.

I think that would be more consistent.

**Comment by pitschr** [comment]
Yes, for DPT5 `getUnsignedValue()` is calculating based on the formula defined by KNX Specification. The other `getRawUnsignedValue()` just returns the value that is encoded in the byte array. It is same value you are passing using `of(int value)`.

Good idea, I may consider to provide `DPT5#of(int)´ (or `DPT5#of(double)` ?) in same way like in ETS. For example, `DPT5.SCALING.of(100)` will return `100` for `getUnsignedValue()` and returns `255` for `getRawUnsignedValue()` which would be same for  `toByteArray()`. Do you see a reason to keep the `getRawUnsignedValue()` method here?

Far as I see it would also affect `DPT7` , `DPT8` and `DPT13`.

**Comment by StefanOltmann** [comment]
> Good idea, I may consider to provide `DPT5#of(int)´ (or `DPT5#of(double)`?) in same way like in ETS.

I think it should be only one `of()` method for every data point and this should take the same type in as ETS.

> For example,`DPT5.SCALING.of(100)`will return`100`for`getUnsignedValue()`and returns`255`for`getRawUnsignedValue()`which would be same for `toByteArray()`. 
> Do you see a reason to keep the `getRawUnsignedValue()` method here?

No and I actually needed to read the JavaDoc to understand how these methods differ and the technical detail behind.

I also don't see great value in the emphasis of "unsigned". Similar to the apci data stuff (and that to need to know what cEMI is) this is technical detail I wouldn't expose.

I suggest to make it more user friendly by just having only one simple `getValue()` that returns the value in the same format as `of()` takes it in and this is identical to what ETS (and therefore the specification?) has.

See that I set up my whole house with the ETS, developed logic with Gira X1 and used openHAB a long time now, used calimero-project (for a short time) and knx-link is the first project that requires me to get to know these details of the protocol. It's super nice how all this is documented and I can read me trough it to understand KNX on a deeper level, but I feel for simple interactions like I want to do the API/library should not force me to.

> Far as I see it would also affect `DPT7` , `DPT8` and `DPT13`.

I did not check for that, but it I think it should apply consistently to all these types of course.

**Comment by pitschr** [comment]
I pushed the changes to "master-2020-01-03" branch. Can you please check if that works for you.

Actually I fixed it for DPT1 - DPT5 only right now, others will be adapted later.
When you now provide e.g. `DPT5.SCALING.of(101)` then you should get error message like 
> KnxNumberOutOfRangeException: Value '101' for argument 'value' is out of range '0'..'100'.

But `DPT5.SCALING.of(100)` should now be internally translated to `0xFF` (=255) as it is 100%

I am forwarding to hear your experience with DPT5 to see if I am on the right track

**Comment by StefanOltmann** [comment]
> I am forwarding to hear your experience with DPT5 to see if I am on the right track

Yes, you are!

I just reviewed the changeset. I like it very much!

**Comment by pitschr** [comment]
DPT1 - DPT16 have been updated. I also made some refactoring (e.g. naming in ETS is bit different than in KNX specification paper for some reasons)

The changes have been merged to master branch. DPT17 - 24 will be fixed as soon I have time again (most probably on weekend. Today is my last vacation day)

**Comment by StefanOltmann** [comment]
Awesome!

**Comment by pitschr** [comment]
DPT17-23 have been committed to master branch as well.

Can you please verify. From my side we can consider this issue as resolved.

**Comment by StefanOltmann** [comment]
Judging from the code review all looks fine! 👍 

I tested it only for DPT1 and DP5, but as soon as I integrated knx-link further I will let you know should I discover problems with the other types.

The API is now very nice and clean! ❤️

**Comment by StefanOltmann** [comment]
Sorry, but I tested it not well enough I guess.

I just tested that setting values like this works correctly.

```
fun main() {

    DefaultKnxClient.createStarted().use { client ->

        val percent = 33;

        client.writeRequest(GroupAddress.of("4/1/2"), DPT5.SCALING.of(percent))
    }
}
```

But I just discovered that `val percentage = percentageDpt.of(item.cemi.data).value` (the byte array argument) throws an exception because of the range.

So the bytes send by ETS (and now knx-core) seem to be still in a 255 base fashion.

Please let me know if you need more input to reproduce this.

**Comment by pitschr** [comment]
ouch ... I only tested the `DPT5.VALUE_1_OCTET_UNSIGNED_COUNT` and not SCALING one. As the `DPT5.VALUE_1_OCTET_UNSIGNED_COUNT` works in 0..255 range the issue was not discovered yet.

I need to add more test cases and also consider the ones which uses calculation function (e.g. SCALING, ANGLE, ..)

**Comment by pitschr** [comment]
Changes pushed to 2020-01-08 branch as well. Far as I see it affects only DPT5, 7 and 8 as they have calculation. For DPT8 I now provided getValueAsInt() and getValuesAsDouble() . The issue is that DPT8 is normally signed int, but DPT8.PERCENT is considered to be floating one. Have not found a better solution for that yet.

Thanks for reporting the issues and improve the library

**Comment by StefanOltmann** [comment]
> 
> Changes pushed to 2020-01-08 branch as well. Far as I see it affects only DPT5, 7 and 8 as they have calculation. For DPT8 I now provided getValueAsInt() and getValuesAsDouble() . The issue is that DPT8 is normally signed int, but DPT8.PERCENT is considered to be floating one. Have not found a better solution for that yet.

DPT5 works well now in both directions. 👍 

As soon as it's available on maven central I will test knx-link in production. :-)

Right now I use calimero project with my Alexa smart home skill and I want to replace it with knx-link because this is a much cleaner and modern solution and therefore a better fit for what I'm building up right now.
 
> Thanks for reporting the issues and helping to improve the library

You're welcome! :)

Thanks for creating this nice project and maintainting it so well.

One day I will try to convert it to Kotlin to make my KNX server a Kotlin/Native app with minimal footprint and eliminate the need for a JVM. I ran trough the automatic Kotlin conversion of IDEA, but there are a lot of places that need manual rework. So this will take a lot of time and first I want to make sure all my devices are properly supported so I do only need to do this once.

**Comment by pitschr** [comment]
committed as 0.2.0 to maven repo. will take few hours until it is officially indexed

**Comment by StefanOltmann** [comment]
My KNX server using knx-link v0.2.0 is now up and running in production.

With calimero project I needed to specify set the local IP on the linux vmware, but knx-link does not seem to need that. In fact it runs out of the box without any configuration. 👍 

I added my heatings as well and can confirm that DPT 9.001 is working correctly.

I will let you know how stable the library is in 24/7 usage and report any crashes. :)

**Comment by pitschr** [comment]
When you report the crashes please also check who initiated the disconnection. If there were 3 unsuccessful ACK then the KNX client will initiate a disconnect; and vice versa when KNX client doesn't respond.

Ideally you may run the audit plugin as well. It is very helpful for diagnosis.
https://github.com/pitschr/knx-link/tree/master/knx-core-plugins/audit
